// Generated by CoffeeScript 1.6.2
(function() {
  var calc;

  calc = angular.module('calc', []);

  calc.controller('CalcCtrl', function($scope) {
    var allowedNumberDigits, calculate, formatResult, operands, result;

    operands = [8, 334];
    allowedNumberDigits = 11;
    $scope.display = operands[operands.length - 1];
    $scope.keys = ['mc', 'm+', 'm-', 'mr', 7, 8, 9, '/', 4, 5, 6, 'x', 1, 2, 3, '-', 0, '.', '=', '+'];
    formatResult = function(result) {
      var _decDigitsNeeded, _indexDot, _intDigits, _numLen, _resS;

      _resS = result.toString();
      _numLen = _resS.length;
      _indexDot = _resS.indexOf('.');
      _intDigits = +_resS.slice(0, _indexDot).length;
      _decDigitsNeeded = allowedNumberDigits - _intDigits - 1;
      return _resS = +result.toFixed(_decDigitsNeeded);
    };
    calculate = function(operator, newOperand) {
      var firstOperand;

      firstOperand = $scope.display;
      switch (operator) {
        case 'x':
          return firstOperand * newOperand;
        case '/':
          if (newOperand === 0) {
            return 'Error';
          }
          return firstOperand / newOperand;
        case '-':
          return firstOperand - newOperand;
        case '+':
          return firstOperand + newOperand;
      }
    };
    result = formatResult(calculate('/', 3));
    if (result !== 'Error') {
      operands.push(result);
      operands.shift();
      return $scope.display = operands[operands.length - 1];
    } else {
      return operands = [];
    }
  });

}).call(this);
