// Generated by CoffeeScript 1.6.2
(function() {
  var calc, calculate, operands, result;

  calc = angular.module('calc', []);

  calc.controller('CalcCtrl', function($scope) {
    $scope.display = operands[operands.length - 1];
    return $scope.keys = ['mc', 'm+', 'm-', 'mr', 7, 8, 9, '/', 4, 5, 6, 'x', 1, 2, 3, '-', 0, '.', '=', '+'];
  });

  operands = [8, 7];

  calculate = function(operator, newOperand) {
    var firstOperand;

    firstOperand = operands[operands.length - 1];
    switch (operator) {
      case 'x':
        return firstOperand * newOperand;
      case '/':
        if (newOperand === 0) {
          return 'Error';
        }
        return operands[0] / newOperand;
      case '-':
        return firstOperand - newOperand;
      case '+':
        return firstOperand + newOperand;
    }
  };

  result = calculate('/', 2);

  if (result !== 'Error') {
    operands.push(result);
    operands.shift();
    $scope.display = result;
  }

}).call(this);
